name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.hashes }}

    steps:
      - uses: actions/checkout@v3

      - name: Build artifacts
        run: |
          echo "artifact1" > artifact1
          echo "artifact2" > artifact2

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          files=$(ls artifact*)
          echo "::set-output name=hashes::$(sha256sum $files | base64 -w0)"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator@v1.4.0
    with:
      base64-subjects: ${{ needs.build.outputs.digests }}
      upload-assets: true
